const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
const FETCH_SINGLE_PRODUCT_BEGIN = "FETCH_SINGLE_PRODUCT_BEGIN";
const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
const FETCH_SINGLE_PRODUCT_ERROR = "FETCH_SINGLE_PRODUCT_ERROR";
const LOAD_PRODUCTS = "LOAD_PRODUCTS";
const SET_GRID = "SET_GRID";
const SET_LIST = "SET_LIST";
const UPDATE_SORT = "UPDATE_SORT";
const SORT_PRODUCTS = "SORT_PRODUCTS";
const UPDATE_FILTERS = "UPDATE_FILTERS";
const FILTER_PRODUCTS = "FILTER_PRODUCTS";

export {
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  FETCH_PRODUCTS_BEGIN,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_ERROR,
  FETCH_SINGLE_PRODUCT_BEGIN,
  FETCH_SINGLE_PRODUCT_SUCCESS,
  FETCH_SINGLE_PRODUCT_ERROR,
  LOAD_PRODUCTS,
  SET_GRID,
  SET_LIST,
  UPDATE_SORT,
  SORT_PRODUCTS,
  UPDATE_FILTERS,
  FILTER_PRODUCTS,
};
